PharmaFriend/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500

urlpatterns = [

    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),

    # For user to go to Admin site
    path('securelogin/', admin.site.urls),

    # For User Access to PharmaFriend
    path('', include('application.urls')),

    # For User Access to  Pharmastore
    path('pharmastore/', include('pharmastore.urls')),

    # To User Access to cart of Pharmastore
    path('pharmastore/cart/', include('carts.urls')),

    # For User Access to account in Pharmastore
    path('pharmastore/accounts/', include('accounts.urls')),
                                          
    # For User to access Order pages
    path('pharmastore/orders/', include('orders.urls')),

    # For user Consulting Doctor
    path('Consult/', include('consultvideo.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = 'application.views.error_500'
handler400 = 'application.views.error_400'
handler404 = 'application.views.error_404'

application/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'pharmafriend'

urlpatterns = [
    #Home page for the user
    path('', views.Homepage, name="homepage"),

    # To search for medicines and get a price comparision
    path('Search/', views.Search, name="searchpage"),

    # To view different medicines
    path('Store/', views.Store, name="storepage"),

    path('Doctor/', views.Doctor, name="doctorpage"),

    path('About/', views.About, name="aboutpage"),

    path('Contact/', views.Contact, name="contactpage"),

    # To get info for website
    path('Medicine/', views.Medicine, name="medicinepage"),

    # Locate the medical store with the required medicines
    path('Locate/', views.Locate, name="locatepage"),

    path('Addmeds/', views.AddMeds, name="addnames"),

    path('GovMeds/', views.GovMeds, name="govmeds"),

    path('SignupMedical/', views.signupaction, name="signupmed"),

    path('LoginMedical/', views.loginaction, name="loginmed"),

    path('Pharmacy/', views.Pharmacy, name="pharmacy"),

    path('Logoutmeds/', views.logoutmeds, name="logoutmeds"),
    
    ]

carts/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'carts'

urlpatterns = [
    #Home page for the user
    path('', views.Cartpage, name="cartpage"),
    path('add_cart/<int:product_id>/', views.add_cart, name="add_cart_page"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name="remove_cart_page"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name="remove_cart_item_page"),
    path('checkoutcart/', views.checkout_cart, name="checkout_cart"),
    ]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('placeorder/', views.PlaceOrder, name="placeorderpage"),
    path('paymentpage/', views.PaymentOrder, name="paymentpage"),
    path('order_complete/', views.OrderComplete, name="ordercomplete"),
]

pharmastore/urls.py
from django.urls import path
from . import views

app_name = 'pharmastore'

urlpatterns = [
    #Home page for the user
    path('', views.Homepage, name="homepage"),
    path('store/', views.Storepage, name="storepage"),
    path('store/category/<slug:category_slug>/', views.Storepage, name="products_by_category"),
    path('store/category/<slug:category_slug>/<slug:product_slug>/', views.Productpage, name="products_view_page"),
    path('store/search/', views.Search, name="searchpage"),
    path('submitreview/<int:product_id>/', views.SubmitReview, name="submit_review"),
    ]

carts/models.py
from django.db import models
from pharmastore.models import Product, Variation
from accounts.models import Account

# Create your models here.
# Cart models is like a container stores a cart instance
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)


    def __str__(self):
        return self.cart_id


"""Cartitem are items present in the cart at the given moment depends on cart with the "cart" variable 
and products are connected with the "product" variable"""
class CartItem(models.Model):
    variation = models.ManyToManyField(Variation, blank=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity
    
    def __unicode__(self):
        return self.product

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from pharmastore.models import Product, Variation
from .models import Cart, CartItem
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from accounts.models import UserProfile

# To get ID of cart from the sessions key
def _cart_id(request):
    # Get Session key 
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

# To add products int he cart
def add_cart(request, product_id):
    current_user = request.user #Get the current user
    product = Product.objects.get(id=product_id) #get the product
    
    if current_user.is_authenticated:
        # If user is authenticated get cart_item on basis of user and product
        product_variation = []
        # Code segment to get variation
        # request.POST = <QueryDict: {'csrfmiddlewaretoken': ['bgbAnmmOWKnc0RH2PGokfuisFg8Y5bR0G7vGjGyg6mKqNXH7ICk2B1Gy2KAXlifC'], 'strips': ['strip of 20'], 'power': ['xt']}> 
        if request.method == 'POST':
            for item in request.POST:
                # item is key something like 'csrfmiddlewaretoken'
                key = item

                # value is taken from dictionary when key is given
                value = request.POST[key]
                try:
                    # get variation from given values
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    
                    # append the said variation to list [this is done one by one first for strips then for power]
                    product_variation.append(variation)
                except:
                    pass

        # Code Segment to get Cart Item
        # check if cartitem exists, returns a boolean value
        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        # if cartitem exists in the gven cart
        if is_cart_item_exists:
            # Will provide us with a single product
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            
            # existing_variations -> database
            # current variation -> product_variation
            # item_id -> database
            
            # Will give all variation associated with the product added in cart
            ex_var_list = []
            id = []
            for item in cart_item:
                # get all variations associated with this item, does this one by one
                existing_variation = item.variation.all()
                
                # Add the variation in the existing one
                ex_var_list.append(list(existing_variation))
                
                # Append the Item ID of the CartItem
                id.append(item.id)

            """product_variation consists of variations done at time of adding to cart and ex_var consists
            of all the variations associated with the item at that particular instant"""
            # So if product variation is found in exiting one just increase quantity by 1            
            
            if product_variation in ex_var_list:
                # get index of product variation found in pehle se hi ex_var_list
                index = ex_var_list.index(product_variation)
                # Since at time of appending the existing variation we also append the id the indexes are same hence access the index
                item_id = id[index]
                # Get the item and increase quantity by 1
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            
            # If item is not found create one
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                # Say for 1 item we are selecting two diff. variations of "XM" n "XT" in that case product_variation list will have 2 variations in it
                if len(product_variation) > 0:
                    # Clear all the variations for the item
                    item.variation.clear()
                    # Add the product_variation list to the item
                    item.variation.add(*product_variation)
                item.save()

        # If cartitem doesn't exist 
        else:
            # Create a cartitem
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                user=current_user,
            )
            # If any variations clear all the add the variation
            if len(product_variation) > 0:
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)
            cart_item.save()
        return redirect('carts:cartpage')
    else:
        # If user is not authenticated then get cartitem on basis of product and cart
        product_variation = []
        # Code segment to get variation
        # request.POST = <QueryDict: {'csrfmiddlewaretoken': ['bgbAnmmOWKnc0RH2PGokfuisFg8Y5bR0G7vGjGyg6mKqNXH7ICk2B1Gy2KAXlifC'], 'strips': ['strip of 20'], 'power': ['xt']}> 
        if request.method == 'POST':
            for item in request.POST:
                # item is key something like 'csrfmiddlewaretoken'
                key = item

                # value is taken from dictionary when key is given
                value = request.POST[key]
                try:
                    # get variation from given values
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    
                    # append the said variation to list [this is done one by one first for strips then for power]
                    product_variation.append(variation)
                except:
                    pass
            
        # Code Segment to get cart
        try:
            # Get Cart on basis of session key
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
            # Save cart in db
        cart.save()

        # Code Segment to get Cart Item
        # check if cartitem exists, returns a boolean value
        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        # if cartitem exists in the gven cart
        if is_cart_item_exists:
            # Will provide us with a single product
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            
            # existing_variations -> database
            # current variation -> product_variation
            # item_id -> database
            
            # Will give all variation associated with the product added in cart
            ex_var_list = []
            id = []
            for item in cart_item:
                # get all variations associated with this item, does this one by one
                existing_variation = item.variation.all()
                
                # Add the variation in the existing one
                ex_var_list.append(list(existing_variation))
                
                # Append the Item ID of the CartItem
                id.append(item.id)

            """product_variation consists of variations done at time of adding to cart and ex_var consists
            of all the variations associated with the item at that particular instant"""
            # So if product variation is found in exiting one just increase quantity by 1            
            
            if product_variation in ex_var_list:
                # get index of product variation found in pehle se hi ex_var_list
                index = ex_var_list.index(product_variation)
                # Since at time of appending the existing variation we also append the id the indexes are same hence access the index
                item_id = id[index]
                # Get the item and increase quantity by 1
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()

            # If item is not found create one
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                # Say for 1 item we are selecting two diff. variations of "XM" n "XT" in that case product_variation list will have 2 variations in it
                if len(product_variation) > 0:
                    # Clear all the variations for the item
                    item.variation.clear()
                    # Add the product_variation list to the item
                    item.variation.add(*product_variation)
                item.save()

        # If cartitem doesn't exist 
        else:
            # Create a cartitem
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart,
            )
            # If any variations clear all the add the variation
            if len(product_variation) > 0:
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)
            cart_item.save()
        return redirect('carts:cartpage')

# To decrement a item from cart one by one or remove a item from the cart if only one instance present
def remove_cart(request, product_id, cart_item_id):
    # Get Cart from cart id
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:        
            cart= Cart.objects.get(cart_id=_cart_id(request))

carts/templates/carts/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>PharmaStore</title>

<!-- <link href="{% static 'pharmastore/images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon"> -->

<!-- jQuery -->
<script src="{% static 'pharmastore/js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'pharmastore/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'pharmastore/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'pharmastore/fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'pharmastore/css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'pharmastore/css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'pharmastore/js/script.js' %}" type="text/javascript"></script>

<link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
<link rel="stylesheet" href="{% static 'application/CSS/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/jquery-ui.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/aos.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/style.css' %}">  

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>
</head>
<body>
    
    <header class="section-header">
        <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
            <div class="site-navbar py-2">
                <div class="container">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="logo">
                    <div class="site-logo">
                        <a href="{% url 'pharmafriend:homepage' %}" class="js-logo-clone">Pharma Friend</a>
                    </div>
                    </div>
                    <div class="main-nav d-none d-lg-block">
                    <nav class="site-navigation text-right text-md-center" role="navigation">
                        <ul class="site-menu js-clone-nav d-none d-lg-block">
                        <li class="active"><a href="{% url 'pharmafriend:homepage' %}">Home</a></li>
                        <li><a href="{% url 'pharmastore:homepage' %}">Store</a></li>
                        <li><a href="{% url 'pharmafriend:searchpage' %}">Search Medicines</a></li>
                        <li><a href="{% url 'pharmafriend:govmeds' %}">Government Vendors</a></li>
                        <li><a href="{% url 'pharmafriend:locatepage' %}">Locate Pharmacy</a></li>
                        <li><a href="{% url 'pharmafriend:aboutpage' %}">About</a></li>
                        <li><a href="{% url 'pharmafriend:contactpage' %}">Contact</a></li>
                        </ul>
                    </nav>
                    </div>
                </div>
            </div>
        </nav>
        
        <section class="header-main border-bottom">
            <div class="container">
        <div class="row align-items-center">
            <div class="col-lg col-sm col-md col-6 flex-grow-0">
                <div class="category-wrap dropdown d-inline-block float-right">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
                         All category 
                    </button>
                    <div class="dropdown-menu">
                        {% for category in links %}
                            <a class="dropdown-item" href="{{category.get_url}}">{{category.category_name}}</a>
                        {% endfor %}
                    </div>
                </div>  <!-- category-wrap.// -->
            </div> <!-- col.// -->
            <a href="{% url 'pharmastore:storepage' %}" class="btn btn-outline-primary">Store</a>
            <div class="col-lg  col-md-6 col-sm-12 col">
                <form action="#" class="search">
                    <div class="input-group w-100">
                        <input type="text" class="form-control" style="width:60%;" placeholder="Search">
                        
                        <div class="input-group-append">
                          <button class="btn btn-primary" type="submit">
                            <i class="fa fa-search"></i>
                          </button>
                        </div>
                    </div>
                </form> <!-- search-wrap .end// -->
            </div> <!-- col.// -->
            <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                        <div class="d-flex justify-content-end mb-3 mb-lg-0">
                            <div class="widget-header">
                                <small class="title text-muted">Welcome guest!</small>
                                <div> 
                                    <a href="./signin.html">Sign in</a> <span class="dark-transp"> | </span>
                                    <a href="./register.html"> Register</a>
                                </div>
                            </div>
                            <a href="{% url 'carts:cartpage' %}" class="widget-header pl-3 ml-3">
                                <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                                <span class="badge badge-pill badge-danger notify">0</span>
                            </a>
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
        </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->
        
        
        
        
    </header> <!-- section-header.// -->
    {% block content %}
        <!-- Content -->
    {% endblock content %}
    
    <!-- ========================= FOOTER ========================= -->
    <footer class="site-footer">
        <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
            <div class="block-7">
                <h3 class="footer-heading mb-4">About Us</h3>
                <p>We are with a mission of providing medicines to the customer at an affordable rate by price comparison and increasing awareness on Medicine prices and relevant information</p>
            </div>  
            </div>
            <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
            <h3 class="footer-heading mb-4">Quick Links</h3>
            <ul class="list-unstyled">
            <li><a href="{% url 'pharmafriend:homepage' %}">Home</a></li>
            <li><a href="{% url 'pharmafriend:searchpage' %}">Search Medicines</a></li>
            <li><a href="{% url 'pharmafriend:govmeds' %}">Government Vendors</a></li>
            <li><a href="{% url 'pharmafriend:locatepage' %}">Locate Pharmacy</a></li>
            <li><a href="{% url 'pharmafriend:pharmacy' %}">Pharmacy Zone</a></li>
            <li><a href="{% url 'pharmafriend:aboutpage' %}">About</a></li>
            <li><a href="{% url 'pharmafriend:contactpage' %}">Contact</a></li>
            </ul>
            </div>

            <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
                <h3 class="footer-heading mb-4">Contact Info</h3>
                <ul class="list-unstyled">
                <li class="address">KJSIET Sion, Mumbai, Maharashtra, India</li>
                <li class="phone"><a>+91 77385 74300</a></li>
                <li class="email"><a href="#" onclick="sendEmail('gammabytessup@gmail.com', 'Communication with GammaBytes', 'BODY');">gammabytessup@gmail.com</a></li>
                </ul>
            </div>
            </div>
        </div>
        
        </div>
        <div class="row pt-5 mt-5 text-center">
            <div class="col-md-12">
            <p>
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved | Website made by Gammabyte Pvt Ltd.
            
            </p>
            </div>

        </div>
    </footer>

    <script>
        function sendEmail(to, subject, body) {
            window.open('https://mail.google.com/mail/u/0/?view=cm&fs=1&to=' + to + '&su=' + subject + '&body=' + body);
        }
    </script>
    <!-- ========================= FOOTER END // ========================= -->

carts/templates/carts/cart.html
{% extends 'pharmastore/base.html' %}
{% load static %}


{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->


{% if not cart_items %}
	<h2 class="text-center">
		<b>
			Your shopping cart is empty!
		</b>
	</h2>
	<br>
	<div class="text-center">
		<a href="{% url 'pharmastore:storepage' %}" class="btn btn-primary">Continue Shopping</a>
	</div>
{% else %}
	
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase" style="text-align: center;">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{% for cart_item in cart_items  %}	
	<tr>
		<td>
			<figure class="itemside align-items-center">
				<div class="aside"><img src="{{cart_item.product.images.url}}" class="img-sm"></div>
				<figcaption class="info">
					<a href="{{cart_item.product.get_url}}" class="title text-dark">{{cart_item.product.product_name}}</a>
					<p class="text-muted small">
						{% if cart_item.variation.all %}
							{% for item in cart_item.variation.all %}
								{{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
							{% endfor %}
						{% endif %}
					</p>
				</figcaption>
			</figure>
		</td>
		<td> 
			<div class="col" style="width: max-content;">
				<div class="input-group input-spinner">
					<div class="input-group-prepend">
					<a href="{% url 'carts:remove_cart_page' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
					</div>
					<input type="text" class="form-control"  value="{{ cart_item.quantity }}">
					<div class="input-group-append">
						<form action="{% url 'carts:add_cart_page' cart_item.product.id %}" method="POST">
							{% csrf_token %}
							{% for item in cart_item.variation.all %}
								<input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst }}">
							{% endfor %}
							<button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
						</form>
					</div>
				</div> <!-- input-group.// -->
			</div> <!-- col.// -->
		</td>
		<td> 
			<div class="price-wrap"> 
				<var class="price">₹{{cart_item.sub_total}}</var> 
				<small class="text-muted"> ₹{{cart_item.product.price}} each </small> 
			</div> <!-- price-wrap .// -->
		</td>
		<td class="text-right"> 
		<a href="{% url 'carts:remove_cart_item_page' cart_item.product.id cart_item.id %}" onclick="return confirm('Are you sure you want to delete this item?')" class="btn btn-danger"> Remove</a>
		</td>
	</tr>
{% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">₹{{total}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ₹{{tax}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>₹{{grnd_tot}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="./images/misc/payments.png" height="26">
			</p>
			<a href="{% url 'carts:checkout_cart' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'pharmastore:storepage' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
{% endif %}
<!-- ========================= SECTION CONTENT END// ========================= -->
</body>
</html>
{% endblock content %}