PharmaFriend/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500

urlpatterns = [

    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),

    # For user to go to Admin site
    path('securelogin/', admin.site.urls),

    # For User Access to PharmaFriend
    path('', include('application.urls')),

    # For User Access to  Pharmastore
    path('pharmastore/', include('pharmastore.urls')),

    # To User Access to cart of Pharmastore
    path('pharmastore/cart/', include('carts.urls')),

    # For User Access to account in Pharmastore
    path('pharmastore/accounts/', include('accounts.urls')),
                                          
    # For User to access Order pages
    path('pharmastore/orders/', include('orders.urls')),

    # For user Consulting Doctor
    path('Consult/', include('consultvideo.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = 'application.views.error_500'
handler400 = 'application.views.error_400'
handler404 = 'application.views.error_404'

accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    path('user/register', views.RegisterUser, name="registeruser"),
    path('user/login', views.LoginUser, name="loginuser"),
    path('user/logout', views.LogoutUser, name="logoutuser"),
    path('user/dashboard', views.DashboardUser, name="dashboarduser"),

    # For Forgor and Rest password functionality
    path('user/forgotpassword', views.ForgotPassword, name="forgetpassword"),
    path('user/resetpassword', views.ResetPasswordForm, name="resetpassword"),

    # For user identification and validation in Account activation
    path('user/activate/<uidb64>/<token>/', views.ActivateUser, name="activateuser"),
    
    # For user identification and validation in Password Reset Request
    path('user/reset_password_validate/<uidb64>/<token>/', views.ResetPasswordValidateUser, name="reset_password_validate"),

    # To access user orders
    path('user/myorders/', views.UserOrders, name="myorders"),
    path('user/orderdetails/<int:order_id>/', views.OrderDetails, name="orderdetails"),
    path('user/editprofile/', views.EditProfile, name="editprofile"),
    path('user/changepasscode/', views.ChangePassword, name="changepassword"),
]

carts/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'carts'

urlpatterns = [
    #Home page for the user
    path('', views.Cartpage, name="cartpage"),
    path('add_cart/<int:product_id>/', views.add_cart, name="add_cart_page"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name="remove_cart_page"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name="remove_cart_item_page"),
    path('checkoutcart/', views.checkout_cart, name="checkout_cart"),
    ]

consultvideo/urls.py
from django.urls import path, re_path
from . import views
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.conf.urls.static import static
# from django.conf import settings

app_name = 'Consult'

urlpatterns = [
    # Send Request to admin requesting room
    path('requestconsult/', views.RequestConsult, name="request_new_consult"),

    path('sendconsult/', views.SendConsult, name="send_consult"),

    # Stream site
    path('room/', views.Consult, name="consult"),

    # My lobby
    path('', views.CreateRoom, name="create_room"),
    
    # Generate Token
    path('tokengen/', views.gettoken, name="tokengen"),
]

accounts/forms.py
from django import forms
from .models import Account, UserProfile
# phone_number
class RegistrationForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput(
    attrs= {
    'placeholder': 'Enter Password',
    'class': 'form-control'}
    ))

    confirm_password = forms.CharField(widget=forms.PasswordInput(
    attrs= {
    'placeholder': 'Confirm Password',
    'class': 'form-control'}
    ))

    class Meta:
        model = Account
        fields = ['first_name',
                   'last_name',
                   'email',
                   'password',
                   'city_location',
                   'phone_no',
                    ] 

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['placeholder'] = "Enter First Name"
        self.fields['last_name'].widget.attrs['placeholder'] = "Enter Last Name"
        self.fields['phone_no'].widget.attrs['placeholder'] = "Enter Phone Number"
        self.fields['email'].widget.attrs['placeholder'] = "Enter Email Address"
        self.fields['city_location'].widget.attrs['placeholder'] = "Enter City Location"
    
    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        cnf_password = cleaned_data.get('confirm_password')

        if password != cnf_password:
            raise forms.ValidationError(
                "Password Does Not Match"
            )
    
class UserForm(forms.ModelForm):
    """Form definition for MODELNAME."""

    class Meta:
        """Meta definition for MODELNAMEform."""

        model = Account
        fields = ('first_name', 'last_name', 'phone_no',)

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class UserProfileForm(forms.ModelForm):
    profile_pic = forms.ImageField(required=False, error_messages = {'invalid':("Image files only")}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ('address_line1', 'address_line2', 'city', 'state', 'country', 'profile_pic',)
    
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        # self.fields['first_name'].widget.attrs['placeholder'] = "Enter First Name"
        # self.fields['last_name'].widget.attrs['placeholder'] = "Enter Last Name"
        # self.fields['phone_no'].widget.attrs['placeholder'] = "Enter Phone Number"
        # self.fields['email'].widget.attrs['placeholder'] = "Enter Email Address"
        # self.fields['city_location'].widget.attrs['placeholder'] = "Enter City Location"

accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from .models import Account, UserProfile
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from carts.models import Cart, CartItem
from carts.views import _cart_id
from orders.models import Order, OrderProduct
from .forms import UserForm, UserProfileForm
from django.shortcuts import get_object_or_404

# Verfification Mail
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

import requests

# Create your views here.
def RegisterUser(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)

        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            city = form.cleaned_data['city_location']
            password = form.cleaned_data['password']
            phone_no = form.cleaned_data['phone_no']
            username = str(email).split('@')[0]

            user = Account.object.create_user(first_name=first_name, last_name=last_name,username=username, email=email,password=password)
            user.city_location = city
            user.phone_no = phone_no
            user.save()

            # When user is created profile is also created in the back
            # Create user profile
            user_profile = UserProfile()
            user_profile.user_id = user.id
            user_profile.profile_pic = 'default/default-user.png'
            user_profile.save()
    
            # User Activation Mail and Activation
            current_site = get_current_site(request)
            mail_subject = "Please Activate your PharmaStore Account"
            message = render_to_string('accounts/account_verification_email.html',{
                'user':user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })

            to_email = email
            send_mail = EmailMessage(mail_subject, message, to=[to_email])
            send_mail.send()
            
            context = {'email':email}
            return render(request, 'accounts/verify_msg.html', context=context)
    else:
        form = RegistrationForm()

    context = {
        'form':form,
    }

    return render(request, 'accounts/register.html', context=context)


def LoginUser(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email = email, password=password)

        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)

                    # Getting the product variations by cart id
                    product_variation = []
                    for item in cart_item:
                        variation = item.variation.all()
                        product_variation.append(list(variation))

                    # Get the cart items from the user to access his product variations
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variation.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    # product_variation = [1, 2, 3, 4, 6]
                    # ex_var_list = [4, 6, 3, 5]

                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                print("Entering in Except")
                pass
            login(request, user)
            messages.success(request, "You are logged in")
            # Grab url from where we came
            url = request.META.get('HTTP_REFERER')
            print(11, url)
            try:
                query = requests.utils.urlparse(url).query
                # next=/cart/checkout/ something similar
                params = dict(x.split('=') for x in query.split('&'))
                # next is key and rest is value
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except:
                return redirect('accounts:dashboarduser')
        else:
            messages.error(request, "Invalid Credentials Entered!")
            return redirect("accounts:loginuser")
    else:
        return render(request, 'accounts/signin.html')

@login_required(login_url = "accounts:loginuser")
def LogoutUser(request):
    logout(request)
    messages.success(request, "You are logged out!")
    return redirect('pharmastore:storepage')

def ActivateUser(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
    
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Congratulations!, Your Account is successfully Activated")
        return redirect("accounts:loginuser")
    else:
        messages.error(request, "Invalid Activation Link")    
        return redirect("accounts:registeruser")

@login_required(login_url = "accounts:loginuser")
def DashboardUser(request):
    orders = Order.objects.order_by('-created_at').filter(user_id=request.user.id, is_ordered=True)
    orders_count = orders.count()
    userprofile = UserProfile.objects.get(user=request.user)

    context = {
        'order_count':orders_count,
        'userprofile': userprofile,
    }
    return render(request, 'accounts/dashboard.html', context=context)

@login_required(login_url = "accounts:loginuser")
def UserOrders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    orders_count = orders.count()


    context = {
        'orders_count': orders_count,
        'orders': orders,
    }
    return render(request, 'orders/my_orders.html', context=context)

@login_required(login_url = "accounts:loginuser")
def EditProfile(request):
    userprofile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        # In order to update current profile use instance
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Your Profile has been updated!")
            return redirect("accounts:editprofile")
    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=userprofile)
    context = {
        'userform': user_form,
        'profileform': profile_form,
        'userprofile': userprofile,
    }
    return render(request, 'accounts/edit_profile.html', context=context)

@login_required(login_url = "accounts:loginuser")
def ChangePassword(request):
    if request.method == 'POST':
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        conf_new_password = request.POST['conf_new_password']

        user = Account.object.get(username__exact=request.user.username)

        if new_password == conf_new_password:
            # Since passwords are hashed we use check_password
            success = user.check_password(current_password)
            if success:
                # Inbuilt fn so as to hash the password
                user.set_password(new_password)
                user.save()
                # auth.logout If require, django will do by-default!
                messages.success(request, "Password Updated successfully")
                return redirect("accounts:changepassword")
            else:
                messages.error(request, "Wrong password entered!")
                return redirect("accounts:changepassword")
        else:
            messages.error(request, "Passwords entered doesn't match!")
            return redirect("accounts:changepassword")
    return render(request, 'accounts/change_password.html')

@login_required(login_url = "accounts:loginuser")
def OrderDetails(request, order_id):
    # Reason to write like this i.e. __ is since order is foreign key to Order from OrderProduct model, 
    # we can access the order_number of Order from OrderProduct using this __
    order_detail = OrderProduct.objects.filter(order__order_number=order_id)

accounts/templates/accounts/account_verification_email.html
{% autoescape off %}

Hii, {{user_first_name}}

Please click on below link to confirm your registration on PharmaStore
http://{{domain}}{% url 'accounts:activateuser' uidb64=uid token=token %}

If you think it's not you, please ignore this email

{% endautoescape %}

accounts/templates/accounts/alert.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container text-center" style="padding-top: 20px;width: 100%;">
            <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert" style="width: 100%;display: table;margin: 0 auto;">
                <!-- <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button> -->
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
                    {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

<script>
    setTimeout(function(){
        document.getElementById('message').fadeOut('slow');
    }, 4000)
</script>

accounts/templates/accounts/change_password.html
{% extends 'pharmastore/base.html' %}

{% block content %}

<section class="section-conten padding-y bg">

{% include 'accounts/alert.html' %}
<div class="container">
	<div class="row">
	{% include 'accounts/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Change Password</strong><br>
		</header>
		<div class="card-body">
			<div class="row">
			<div class="col-md-12">
				<form action="{% url 'accounts:changepassword' %}" method="POST"">
					{% csrf_token %}
					<div class="form-group">
						<label>Current Password:</label>
						<input class="form-control" placeholder="Enter current password" type="password" name="current_password" id="" required>
					</div>
					<div class="form-group">
						<label>New Password:</label>
						<input class="form-control" placeholder="Enter new password" type="password" name="new_password" id="" required>
					</div>
					<div class="form-group">
						<label>Confirm New Password:</label>
						<input class="form-control" placeholder="Confirm new password" type="password" name="conf_new_password" id="" required>
					</div>
					<input class="btn btn-primary" type="submit" value="Submit">
				</form>
			</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends 'pharmastore/base.html' %}
{% load static %}


{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
{% include 'accounts/alert.html' %}
<section class="section-conten padding-y bg">
<div class="container">
	<div class="row">
	{% include 'accounts/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
			<header class="card-header">
				<strong class="d-inline-block mr-3">Logged in as: <span>{{user.first_name}} {{user.last_name}}</span></strong>
			</header>
			<div class="card-body text-dark">
				<div class="row"> 
					<div class="col-md-6">
						<div class="card" style="text-align: center;height: 100%;display: flex;justify-content: center;align-items: center;">
							<div class="card-body">
								<h5 class="card-title">Total Orders</h5>
								<h4>{{order_count}}</h4>
								<a href="{% url 'accounts:myorders' %}">View Orders</a>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="card" style="text-align: center;">
							<div class="card-body">
								<img src="{{userprofile.profile_pic.url}}" alt="User Profile Picture" width="50" height="50" style="border-radius:50%;">
								<p>{{user.email}}</p>
								<p>{{user.phone_no}}</p>
							</div>
						</div>
					</div>
				</div> <!-- row.// -->
			</div> <!-- card-body .// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>
{% endblock content %}

accounts/templates/accounts/dashboard_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        <a class="list-group-item {% if '/dashboard' in request.path %}active{% endif %}" href="{% url 'accounts:dashboarduser' %}">Dashboard</a>
        <a class="list-group-item {% if '/myorders/' in request.path %}active{% endif %}" href="{% url 'accounts:myorders'%}">Orders </a>
        <a class="list-group-item {% if '/editprofile/' in request.path %}active{% endif %}" href="{% url 'accounts:editprofile' %}"> Edit Profile </a>
        <!-- <a class="list-group-item" href="#"> Return and refunds </a> -->
        <a class="list-group-item {% if '/changepasscode/' in request.path %}active{% endif %}" href="{% url 'accounts:changepassword' %}">Change Password</a>
        <!-- <a class="list-group-item" href="#"> My Selling Items </a> -->

        
        {% if user.is_staff %}
            <a class="list-group-item" href="{% url 'Consult:create_room' %}"> Create Consult Room </a>
        {% endif %}
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="#"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
    <!--   SIDEBAR .//END   -->
</aside>

accounts/templates/accounts/edit_profile.html
{% extends 'pharmastore/base.html' %}

{% block content %}

<section class="section-conten padding-y bg">

{% include 'accounts/alert.html' %}
<div class="container">
	<div class="row">
	{% include 'accounts/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Edit Your Profile</strong><br>
		</header>
		<div class="card-body">
			<div class="text-right">
				<img src="{{userprofile.profile_pic.url}}" alt="profile_picture" width="100" style="border-radius: 50px;">
			</div>
			<div class="row">
			<div class="col-md-12">
				<form action="{% url 'accounts:editprofile' %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-row">
						<div class="form-group col-md-6">
							<label>First Name:</label>
							{{userform.first_name}}
						</div>
						<div class="form-group col-md-6">
							<label>Last Name:</label>
							{{userform.last_name}}
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-md-6">
							<label>Phone No:</label>
							{{userform.phone_no}}
						</div>
						<div class="form-group col-md-6">
							<label>Profile Picture:</label>
							{{profileform.profile_pic}}
						</div>
					</div>
					<div class="form-group">
						<label>Address Line-1:</label>
						{{profileform.address_line1}}
					</div>
					<div class="form-group">
						<label>Address Line-2:</label>
						{{profileform.address_line2}}
					</div>
					<div class="form-row">
						<div class="form-group col-md-4">
							<label>City:</label>
							{{profileform.city}}
						</div>
						<div class="form-group col-md-4">
							<label>State:</label>
							{{profileform.state}}
						</div>
						<div class="form-group col-md-4">
							<label>Country:</label>
							{{profileform.country}}
						</div>
					</div>
					<input class="btn btn-primary" type="submit" value="Save">
				</form>
			</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

accounts/templates/accounts/forgotpassword.html
{% extends 'pharmastore/base.html' %}
{% load static %}


{% block content %}
<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
    {% include 'accounts/alert.html' %}  
    <div class="card-body">
      <h4 class="card-title mb-4" style="color: black;">Forgot Password</h4>
      <form action="{% url 'accounts:forgetpassword' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
		    <input type="text" class="form-control" placeholder="Enter Email Address" name="email">
        </div> <!-- form-group// -->

        
        <div class="form-group">
            <button type="submit" class="btn btn-outline-primary btn-block"> Submit  </button>
        </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Already have Password? <a href="{% url 'accounts:loginuser' %}">Login</a></p>
{% endblock content %}
    

accounts/templates/accounts/register.html
{% extends 'pharmastore/base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content" style="color: black;">
<!-- ============================ COMPONENT REGISTER   ================================= -->
	
	<div class="card mx-auto" style="max-width:520px;margin-top: 40px;">
		{% include 'accounts/alert.html' %}
		<article class="card-body">
		<header class="mb-4"><h4 class="card-title">Sign up</h4></header>
		<form action="{% url 'accounts:registeruser' %}" method="POST">
			{% csrf_token %}
			<div class="form-row">
				<div class="col form-group">
					<label>First name</label>
				  	{{form.first_name}}
				</div> <!-- form-group end.// -->
				<div class="col form-group">
					<label>Last name</label>
				  	{{form.last_name}}
				</div> <!-- form-group end.// -->
			</div> <!-- form-row end.// -->
			<div class="form-group">
				<label>Email</label>
				{{form.email}}
				<small class="form-text text-muted">We'll never share your email with anyone else.</small>
				<p style="color: red;">{{form.email.error}}</p>
			</div> <!-- form-group end.// -->
			<div class="form-row">
				<div class="form-group col-md-6">
				  <label>City</label>
				  {{form.city_location}}
				</div> <!-- form-group end.// -->
				<div class="form-group col-md-6">
					<label>Phone No:</label>
					{{form.phone_no}}
				  </div> <!-- form-group end.// -->
			</div> <!-- form-row.// -->
			<div class="form-row">
				<div class="form-group col-md-6">
					<label>Create password</label>
				    {{form.password}}
				</div> <!-- form-group end.// --> 
				<div class="form-group col-md-6">
					<label>Repeat password</label>
				    {{form.confirm_password}}
				</div> <!-- form-group end.// -->  
			</div>
			<p style="color: red;">{{form.non_field_errors}}</p>
			<div class="form-group">
			    <button type="submit" class="btn btn-primary btn-block"> Register  </button>
			</div> <!-- form-group// -->      
			        
			</form>
		</article><!-- card-body.// -->
    </div> <!-- card .// -->
    <p class="text-center mt-4">Have an account? <a href="{% url 'accounts:loginuser' %}">Log In</a></p>
    <br><br>
<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>
{% endblock content %}
</body>
</html>

accounts/templates/accounts/reset_password.html
{% extends 'pharmastore/base.html' %}
{% load static %}


{% block content %}
<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
    {% include 'accounts/alert.html' %}  
    <div class="card-body">
      <h4 class="card-title mb-4" style="color: black;">Reset Password</h4>
      <form action="{% url 'accounts:resetpassword' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
		    <input type="password" class="form-control" placeholder="Enter New Password" name="new_password">
        </div> <!-- form-group// -->

        <div class="form-group">
          <input type="password" class="form-control" placeholder="Confirm New Password" name="conf_password">
          </div> <!-- form-group// -->

        
        <div class="form-group">
            <button type="submit" class="btn btn-outline-primary btn-block"> Submit  </button>
        </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->
{% endblock content %}

accounts/templates/accounts/reset_password_email.html
{% autoescape off %}

Hii, {{user_first_name}}

As Requested, below is the link to restore the password for your PharmaStore account.
http://{{domain}}{% url 'accounts:reset_password_validate' uidb64=uid token=token %}

If you think it's not you, please ignore this email

{% endautoescape %}

accounts/templates/accounts/signin.html
{% extends 'pharmastore/base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content" style="min-height:84vh;color: black;">
<!-- ============================ COMPONENT LOGIN   ================================= -->


{% if request.GET.command == 'verification' %}
  <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px;margin-top: 100px;">
    Thank You for registering with PharmaStore, We have sent a verification email to you registered email address <b>{{request.GET.email}}</b> 
    <br><br>
    Already Verified? <a href="{% url 'accounts:loginuser' %}">Login</a> 
  </div>
{% else %}
	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
    {% include 'accounts/alert.html' %}  
    <div class="card-body">
      <h4 class="card-title mb-4">Sign in</h4>
      <form action="{% url 'accounts:loginuser' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
		    <input type="text" class="form-control" placeholder="Enter Email Address" name="email">
        </div> <!-- form-group// -->
        
        <div class="form-group">
		    <input type="password" class="form-control" placeholder="Enter Password" name="password">
        </div> <!-- form-group// -->
        
        <div class="form-group">
        	<a href="{% url 'accounts:forgetpassword' %}" class="float-right">Forgot password?</a> 
        </div> <!-- form-group form-check .// -->
        
        <div class="form-group">
            <button type="submit" class="btn btn-outline-primary btn-block"> Login  </button>
        </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
  </div> <!-- card .// -->
  <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:registeruser' %}">Sign up</a></p>
  <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->
{% endif %}

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

accounts/templates/accounts/verify_msg.html
{% extends 'pharmastore/base.html' %}
{% load static %}


{% block content %}
    <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px;margin-top: 100px;">
        Thank You for registering with PharmaStore, We have sent a verification email to your registered email address <b>{{email}}</b> 
        <br><br>
        Already Verified? <a href="{% url 'accounts:loginuser' %}">Login</a> 
    </div>
{% endblock content %}
    