PharmaFriend/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500

urlpatterns = [

    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),

    # For user to go to Admin site
    path('securelogin/', admin.site.urls),

    # For User Access to PharmaFriend
    path('', include('application.urls')),

    # For User Access to  Pharmastore
    path('pharmastore/', include('pharmastore.urls')),

    # To User Access to cart of Pharmastore
    path('pharmastore/cart/', include('carts.urls')),

    # For User Access to account in Pharmastore
    path('pharmastore/accounts/', include('accounts.urls')),
                                          
    # For User to access Order pages
    path('pharmastore/orders/', include('orders.urls')),

    # For user Consulting Doctor
    path('Consult/', include('consultvideo.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = 'application.views.error_500'
handler400 = 'application.views.error_400'
handler404 = 'application.views.error_404'

accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    path('user/register', views.RegisterUser, name="registeruser"),
    path('user/login', views.LoginUser, name="loginuser"),
    path('user/logout', views.LogoutUser, name="logoutuser"),
    path('user/dashboard', views.DashboardUser, name="dashboarduser"),

    # For Forgor and Rest password functionality
    path('user/forgotpassword', views.ForgotPassword, name="forgetpassword"),
    path('user/resetpassword', views.ResetPasswordForm, name="resetpassword"),

    # For user identification and validation in Account activation
    path('user/activate/<uidb64>/<token>/', views.ActivateUser, name="activateuser"),
    
    # For user identification and validation in Password Reset Request
    path('user/reset_password_validate/<uidb64>/<token>/', views.ResetPasswordValidateUser, name="reset_password_validate"),

    # To access user orders
    path('user/myorders/', views.UserOrders, name="myorders"),
    path('user/orderdetails/<int:order_id>/', views.OrderDetails, name="orderdetails"),
    path('user/editprofile/', views.EditProfile, name="editprofile"),
    path('user/changepasscode/', views.ChangePassword, name="changepassword"),
]

application/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'pharmafriend'

urlpatterns = [
    #Home page for the user
    path('', views.Homepage, name="homepage"),

    # To search for medicines and get a price comparision
    path('Search/', views.Search, name="searchpage"),

    # To view different medicines
    path('Store/', views.Store, name="storepage"),

    path('Doctor/', views.Doctor, name="doctorpage"),

    path('About/', views.About, name="aboutpage"),

    path('Contact/', views.Contact, name="contactpage"),

    # To get info for website
    path('Medicine/', views.Medicine, name="medicinepage"),

    # Locate the medical store with the required medicines
    path('Locate/', views.Locate, name="locatepage"),

    path('Addmeds/', views.AddMeds, name="addnames"),

    path('GovMeds/', views.GovMeds, name="govmeds"),

    path('SignupMedical/', views.signupaction, name="signupmed"),

    path('LoginMedical/', views.loginaction, name="loginmed"),

    path('Pharmacy/', views.Pharmacy, name="pharmacy"),

    path('Logoutmeds/', views.logoutmeds, name="logoutmeds"),
    
    ]

carts/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'carts'

urlpatterns = [
    #Home page for the user
    path('', views.Cartpage, name="cartpage"),
    path('add_cart/<int:product_id>/', views.add_cart, name="add_cart_page"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name="remove_cart_page"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name="remove_cart_item_page"),
    path('checkoutcart/', views.checkout_cart, name="checkout_cart"),
    ]

consultvideo/urls.py
from django.urls import path, re_path
from . import views
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.conf.urls.static import static
# from django.conf import settings

app_name = 'Consult'

urlpatterns = [
    # Send Request to admin requesting room
    path('requestconsult/', views.RequestConsult, name="request_new_consult"),

    path('sendconsult/', views.SendConsult, name="send_consult"),

    # Stream site
    path('room/', views.Consult, name="consult"),

    # My lobby
    path('', views.CreateRoom, name="create_room"),
    
    # Generate Token
    path('tokengen/', views.gettoken, name="tokengen"),
]

pharmastore/urls.py
from django.urls import path
from . import views

app_name = 'pharmastore'

urlpatterns = [
    #Home page for the user
    path('', views.Homepage, name="homepage"),
    path('store/', views.Storepage, name="storepage"),
    path('store/category/<slug:category_slug>/', views.Storepage, name="products_by_category"),
    path('store/category/<slug:category_slug>/<slug:product_slug>/', views.Productpage, name="products_view_page"),
    path('store/search/', views.Search, name="searchpage"),
    path('submitreview/<int:product_id>/', views.SubmitReview, name="submit_review"),
    ]

pharmastore/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    man_date = models.DateTimeField()
    exp_date = models.DateTimeField()
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modified_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    def get_url(self):
        return reverse('pharmastore:products_view_page', args=[self.category.slug, self.slug])

    def __str__(self):
        return str(self.product_name)
    
    def get_usd_price(self):
        return float("{:.2f}".format(self.price*0.0125))
    
    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def getavgreviewCount(self):
        reviewcount = ReviewRating.objects.filter(product=self, status=True).count()
        return reviewcount


class VariationManager(models.Manager):
    def strips(self):
        return super(VariationManager, self).filter(variation_category='strips', is_active='True')
    
    def power(self):
        return super(VariationManager, self).filter(variation_category='power', is_active='True')
    

variation_category_choice = (
    ('strips', 'strips'),
    ('power', 'power'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    creadted_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __unicode__(self):
        return self.product

class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class ProductGalllery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=f'store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

pharmastore/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']
        

pharmastore/views.py
from django.shortcuts import render, get_object_or_404, redirect
from pharmastore.models import Product, ReviewRating, ProductGalllery
from category.models import Category
from django.shortcuts import HttpResponse
from carts.models import Cart, CartItem
from carts.views import _cart_id
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.contrib import messages
from .forms import ReviewForm
from orders.models import Order, OrderProduct

# Create your views here.
def Homepage(request):
    reviews = None
    products = Product.objects.all().filter(is_available=True).order_by('-created_date')

    for product in products:
        reviews = ReviewRating.objects.filter(product_id=product.id, status=True)

    context = {
        'products': products,
        'reviews': reviews,
    }

    return render(request, 'pharmastore/index.html', context=context)

def Storepage(request, category_slug=None):
    categories = None
    products = None
    product_count = 0

    if category_slug != None:
        # Get products on the basis of category
        categories = get_object_or_404(Category, slug = category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 6)
        page = request.GET.get('page') #Get the 'page' keyword from the URL i.e. ?page=2
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        # Get products irrespective of category
        products = Product.objects.all().filter(is_available=True).order_by('-created_date')
        paginator = Paginator(products, 6)
        page = request.GET.get('page') #Get the 'page' keyword from the URL i.e. ?page=2
        paged_products = paginator.get_page(page)
        product_count = products.count()

    # To add false or inflated value so as to strike it through
    for i in range(len(paged_products)):
        paged_products[i].infprice = paged_products[i].price + (paged_products[i].price * 15/100)

    context = {
        'products': paged_products,
        'products_count': product_count,
    }
    
    return render(request, 'pharmastore/store.html', context=context)

def Productpage(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
    
    except Exception as e:
        raise e
    
    if request.user.is_authenticated:
        try:
            order_product = OrderProduct.objects.filter(user=request.user, product_id = single_product.id).exists()
        except OrderProduct.DoesNotExist:
            order_product = None
    else:
        order_product = None

    product_review = ReviewRating.objects.filter(product_id=single_product.id, status=True)

    product_gallery = ProductGalllery.objects.filter(product_id=single_product.id)
    
    context = {
        'single_product': single_product,
        'in_cart':in_cart,
        'order_product': order_product,
        'product_review': product_review,
        'product_gallery': product_gallery,
    }

    return render(request, 'pharmastore/product-detail.html', context=context)

def Search(request, category_slug=None):
    keyword = None
    products = None
    product_count = None
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()
            
            for i in range(len(products)):
                products[i].infprice = products[i].price + (products[i].price * 15/100)

    context = {
        "keyword": keyword,
        "products": products,
        "products_count":product_count,
    }
    return render(request, 'pharmastore/search-result.html', context=context)

def SubmitReview(request, product_id):
    url = request.META.get('HTTP_REFERER')
    print(1, url)
    if request.method == 'POST':
        try:
            review = ReviewRating.objects.get(user__id = request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=review)
            form.save()
            messages.success(request, "Thank You! Your review has been updated")
            return redirect(url)

        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.review = form.cleaned_data['review']
                data.rating = form.cleaned_data['rating']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, "Thank You! Your review has been updated")
                
                return redirect(url)
            
 

pharmastore/templates/pharmastore/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>PharmaStore</title>

<!-- Paypal Script -->
<script src="https://www.paypal.com/sdk/js?client-id=AXY5ekN44lunpxX4-oGForSjQP-6WSH-vy9ghHQIZirg1uUfgw--tiKhKETa3tDod8pqCN0RqITUzc0Z&enable-funding=venmo&currency=USD" data-sdk-integration-source="button-factory"></script>

<!-- <link href="{% static 'pharmastore/images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon"> -->

<!-- jQuery -->
<script src="{% static 'pharmastore/js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'pharmastore/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'pharmastore/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'pharmastore/fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'pharmastore/css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'pharmastore/css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'pharmastore/js/script.js' %}" type="text/javascript"></script>

<!-- html2pdf.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Link to custom CSS for review and rating -->
<link rel="stylesheet" href="{% static 'pharmastore/css/ratingreview.css' %}">

<link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
<link rel="stylesheet" href="{% static 'application/CSS/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/jquery-ui.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/aos.css' %}">
<link rel="stylesheet" href="{% static 'application/CSS/style.css' %}">

<!-- Jquery CDN -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>
</head>
<body>
    
    <header class="section-header">
        <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
            <div class="site-navbar py-2">
                <div class="container">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="logo">
                    <div class="site-logo">
                        <a href="{% url 'pharmafriend:homepage' %}" class="js-logo-clone">Pharma Friend</a>
                    </div>
                    </div>
                    <div class="main-nav d-none d-lg-block">
                    <nav class="site-navigation text-right text-md-center" role="navigation">
                        <ul class="site-menu js-clone-nav d-none d-lg-block">
                        <li><a href="{% url 'pharmafriend:homepage' %}">Home</a></li>
                        <li class="active"><a href="{% url 'pharmastore:homepage' %}">Store</a></li>
                        <li><a href="{% url 'Consult:create_room' %}">Consult</a></li>
                        <li><a href="{% url 'pharmafriend:searchpage' %}">Search Medicines</a></li>
                        <li><a href="{% url 'pharmafriend:govmeds' %}">Government Vendors</a></li>
                        <li><a href="{% url 'pharmafriend:locatepage' %}">Locate Pharmacy</a></li>
                        <li><a href="{% url 'pharmafriend:aboutpage' %}">About</a></li>
                        </ul>
                    </nav>
                    </div>
                </div>
            </div>
        </nav>
        
        <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
                             All category 
                        </button>
                        <div class="dropdown-menu">
                            {% for category in links %}
                                <a class="dropdown-item" href="{{category.get_url}}">{{category.category_name}}</a>
                            {% endfor %}
                        </div>
                    </div>  <!-- category-wrap.// -->
                </div> <!-- col.// -->
                <a href="{% url 'pharmastore:storepage' %}" class="btn btn-outline-primary">Store</a>
                <div class="col-lg  col-md-6 col-sm-12 col">
                    <form action="{% url 'pharmastore:searchpage' %}" class="search" method="get">
                        <div class="input-group w-100">
                            <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">
                            <div class="input-group-append">
                              <button class="btn btn-primary" type="submit">
                                <i class="fa fa-search"></i>
                              </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->
                <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div>
                        <div class="d-flex justify-content-end mb-3 mb-lg-0">
                            
                            {% if user.id is None %}   
                                <div class="widget-header">
                                    <small class="title text-muted">Welcome guest!</small>
                                    <div>
                                        <a href="{% url 'accounts:loginuser' %}">Sign in</a> <span class="dark-transp"> | </span>
                                        <a href="{% url 'accounts:registeruser' %}"> Register</a>
                                    </div>
                                </div>
                            {% else %}
                                <div class="widget-header">
                                    <small class="title text-muted">Welcome {{user.first_name}}</small>
                                    <div> 
                                        <a href="{% url 'accounts:logoutuser' %}">Logout</a> <span class="dark-transp"> | </span>
                                        <a href="{% url 'accounts:dashboarduser' %}"> Dashboard</a>
                                    </div>
                                </div>
                            {% endif %}
                            <a href="{% url 'carts:cartpage' %}" class="widget-header pl-3 ml-3">
                                <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                                <span class="badge badge-pill badge-danger notify">{{cart_quantity}}</span>
                            </a>
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div>
        </div> <!-- container.// -->
        </section> <!-- header-main .// -->
        
        
        
        
    </header> <!-- section-header.// -->
    {% block content %}
        <!-- Content -->
    {% endblock content %}
    
    <!-- ========================= FOOTER ========================= -->
    <footer class="site-footer">
        <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
            <div class="block-7">
                <h3 class="footer-heading mb-4">About Us</h3>
                <p>We are with a mission of providing medicines to the customer at an affordable rate by price comparison and increasing awareness on Medicine prices and relevant information</p>
            </div>  
            </div>
            <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
            <h3 class="footer-heading mb-4">Quick Links</h3>
            <ul class="list-unstyled">
            <li><a href="{% url 'pharmafriend:homepage' %}">Home</a></li>
            <li><a href="{% url 'pharmafriend:searchpage' %}">Search Medicines</a></li>
            <li><a href="{% url 'pharmafriend:govmeds' %}">Government Vendors</a></li>
            <li><a href="{% url 'pharmafriend:locatepage' %}">Locate Pharmacy</a></li>
            <li><a href="{% url 'pharmafriend:pharmacy' %}">Pharmacy Zone</a></li>
            </ul>
            </div>

            <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
                <h3 class="footer-heading mb-4">Contact Info</h3>
                <ul class="list-unstyled">
                <li class="address">KJSIT Sion, Mumbai, Maharashtra, India</li>
                <li class="phone"><a>+91 77385 74300</a></li>
                <li class="email"><a href="#" onclick="sendEmail('gammabytessup@gmail.com', 'Communication with GammaBytes', 'BODY');">gammabytessup@gmail.com</a></li>
                </ul>
            </div>
            </div>
        </div>
        
        </div>
        <div class="row pt-5 mt-5 text-center">
            <div class="col-md-12">
            <p>
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved | Website made by Gammabyte Pvt Ltd.
            
            </p>
            </div>

        </div>
    </footer>

    <script>
        function sendEmail(to, subject, body) {
            window.open('https://mail.google.com/mail/u/0/?view=cm&fs=1&to=' + to + '&su=' + subject + '&body=' + body);
        }
    </script>
    <!-- ========================= FOOTER END // ========================= -->

pharmastore/templates/pharmastore/store.html
<!-- Has a add to cart feature and all details together -->
{% extends 'pharmastore/base.html' %}
{% load static %}


{% block content %}
<!-- ========================= SECTION PAGETOP ========================= -->
<!-- ========================= SECTION INTRO END// ========================= -->
<!-- ========================= SECTION CONTENT ========================= -->
{% include 'accounts/alert.html' %}
<section class="section-content padding-y">
<div class="container">

<div class="row">
	<aside class="col-md-3">
		
<div class="card">
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Categories</h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_1">
			<div class="card-body">
				
				<ul class="list-menu">
					<li><a href="{% url 'pharmastore:storepage' %}">All Products</a></li>
					{% for category in links %}
					<li><a href="{{category.get_url}}">{{category.category_name}}</a></li>
					{% endfor %}
				</ul>

			</div> <!-- card-body.// -->
		</div>
	</article> <!-- filter-group  .// -->

	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Price range </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_3">
			<div class="card-body">
				<div class="form-row">
				<div class="form-group col-md-6">
				  <label>Min</label>
				  <!-- <input class="form-control" placeholder="$0" type="number"> -->
				  	<select class="mr-2 form-control">
						<option value="0">₹0</option>
						<option value="50">₹50</option>
						<option value="100">₹100</option>
						<option value="150">₹150</option>
						<option value="200">₹200</option>
						<option value="500">₹500</option>
						<option value="1000">₹1000</option>
					</select>
				</div>
				<div class="form-group text-right col-md-6">
				  <label>Max</label>
				  	<select class="mr-2 form-control">
						<option value="50">₹50</option>
						<option value="100">₹100</option>
						<option value="150">₹150</option>
						<option value="200">₹200</option>
						<option value="500">₹500</option>
						<option value="1000">₹1000</option>
						<option value="2000">₹2000+</option>
					</select>
				</div>
				</div> <!-- form-row.// -->
				<button class="btn btn-block btn-primary">Apply</button>
			</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<main class="col-md-9">

<header class="border-bottom mb-4 pb-3">
		<div class="form-inline">
			<span class="mr-md-auto"> <b style="color: black;font-weight: 400;">{{products_count}}</b> Items found </span>
			
		</div>
</header><!-- sect-heading -->

<div class="row">
	{% for product in products %}
	<div class="col-md-4">
		<figure class="card card-product-grid">
			<div class="img-wrap"> 
				<a href="{{product.get_url}}"><img src="{{product.images.url}}"></a>
			</div> <!-- img-wrap.// -->
			<figcaption class="info-wrap">
				<div class="fix-height">
					<a href="{{product.get_url}}" class="title">{{product.product_name}}</a>
					<div class="price-wrap mt-2">
						<span class="price">₹ {{product.price}}</span>
						<del class="price-old">₹ {{product.infprice}}</del>
					</div> <!-- price-wrap.// -->
				</div>
				<a href="{{product.get_url}}" class="btn btn-block btn-info">View Medicine</a>
			</figcaption>
		</figure>
	</div> <!-- col.// -->
	{% endfor %}
</div> <!-- row end.// -->


{% if products.has_other_pages %}	
	<nav class="mt-4" aria-label="Page navigation sample">
	<ul class="pagination">
		
		<!-- For previous page button -->
		{% if products.has_previous %}	
			<li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">Previous</a></li>
		{% else %}
			<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
		{% endif %}

		
		{% for i in products.paginator.page_range %}
			{% if products.number == i %}
				<li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
			{% else %}
				<li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
			{% endif %}
		{% endfor %}
			
		<!-- For next page button -->
		{% if products.has_next %}	
			<li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
		{% else %}
			<li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
		{% endif %}
	</ul>
	</nav>
{% endif %}
	</main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>
{% endblock content %}