PharmaFriend/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500

urlpatterns = [

    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),

    # For user to go to Admin site
    path('securelogin/', admin.site.urls),

    # For User Access to PharmaFriend
    path('', include('application.urls')),

    # For User Access to  Pharmastore
    path('pharmastore/', include('pharmastore.urls')),

    # To User Access to cart of Pharmastore
    path('pharmastore/cart/', include('carts.urls')),

    # For User Access to account in Pharmastore
    path('pharmastore/accounts/', include('accounts.urls')),
                                          
    # For User to access Order pages
    path('pharmastore/orders/', include('orders.urls')),

    # For user Consulting Doctor
    path('Consult/', include('consultvideo.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = 'application.views.error_500'
handler400 = 'application.views.error_400'
handler404 = 'application.views.error_404'

accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    path('user/register', views.RegisterUser, name="registeruser"),
    path('user/login', views.LoginUser, name="loginuser"),
    path('user/logout', views.LogoutUser, name="logoutuser"),
    path('user/dashboard', views.DashboardUser, name="dashboarduser"),

    # For Forgor and Rest password functionality
    path('user/forgotpassword', views.ForgotPassword, name="forgetpassword"),
    path('user/resetpassword', views.ResetPasswordForm, name="resetpassword"),

    # For user identification and validation in Account activation
    path('user/activate/<uidb64>/<token>/', views.ActivateUser, name="activateuser"),
    
    # For user identification and validation in Password Reset Request
    path('user/reset_password_validate/<uidb64>/<token>/', views.ResetPasswordValidateUser, name="reset_password_validate"),

    # To access user orders
    path('user/myorders/', views.UserOrders, name="myorders"),
    path('user/orderdetails/<int:order_id>/', views.OrderDetails, name="orderdetails"),
    path('user/editprofile/', views.EditProfile, name="editprofile"),
    path('user/changepasscode/', views.ChangePassword, name="changepassword"),
]

application/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'pharmafriend'

urlpatterns = [
    #Home page for the user
    path('', views.Homepage, name="homepage"),

    # To search for medicines and get a price comparision
    path('Search/', views.Search, name="searchpage"),

    # To view different medicines
    path('Store/', views.Store, name="storepage"),

    path('Doctor/', views.Doctor, name="doctorpage"),

    path('About/', views.About, name="aboutpage"),

    path('Contact/', views.Contact, name="contactpage"),

    # To get info for website
    path('Medicine/', views.Medicine, name="medicinepage"),

    # Locate the medical store with the required medicines
    path('Locate/', views.Locate, name="locatepage"),

    path('Addmeds/', views.AddMeds, name="addnames"),

    path('GovMeds/', views.GovMeds, name="govmeds"),

    path('SignupMedical/', views.signupaction, name="signupmed"),

    path('LoginMedical/', views.loginaction, name="loginmed"),

    path('Pharmacy/', views.Pharmacy, name="pharmacy"),

    path('Logoutmeds/', views.logoutmeds, name="logoutmeds"),
    
    ]

carts/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'carts'

urlpatterns = [
    #Home page for the user
    path('', views.Cartpage, name="cartpage"),
    path('add_cart/<int:product_id>/', views.add_cart, name="add_cart_page"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name="remove_cart_page"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name="remove_cart_item_page"),
    path('checkoutcart/', views.checkout_cart, name="checkout_cart"),
    ]

consultvideo/urls.py
from django.urls import path, re_path
from . import views
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.conf.urls.static import static
# from django.conf import settings

app_name = 'Consult'

urlpatterns = [
    # Send Request to admin requesting room
    path('requestconsult/', views.RequestConsult, name="request_new_consult"),

    path('sendconsult/', views.SendConsult, name="send_consult"),

    # Stream site
    path('room/', views.Consult, name="consult"),

    # My lobby
    path('', views.CreateRoom, name="create_room"),
    
    # Generate Token
    path('tokengen/', views.gettoken, name="tokengen"),
]

pharmastore/urls.py
from django.urls import path
from . import views

app_name = 'pharmastore'

urlpatterns = [
    #Home page for the user
    path('', views.Homepage, name="homepage"),
    path('store/', views.Storepage, name="storepage"),
    path('store/category/<slug:category_slug>/', views.Storepage, name="products_by_category"),
    path('store/category/<slug:category_slug>/<slug:product_slug>/', views.Productpage, name="products_view_page"),
    path('store/search/', views.Search, name="searchpage"),
    path('submitreview/<int:product_id>/', views.SubmitReview, name="submit_review"),
    ]

application/models.py
from django.db import models

# Create your models here.
class MedicineDet(models.Model):
    medadd = models.CharField(max_length=100)
    medowner = models.CharField(max_length=50)
    medcontact = models.CharField(max_length=20) 
    medshop = models.CharField(max_length=100)
    medname = models.CharField(max_length=100)
    medextra = models.CharField(max_length=50)
    medpow = models.CharField(max_length=100)
    medquan = models.CharField(max_length=50)
    medexp = models.CharField(max_length=100)

    def __str__(self):
        return self.medshop + '->' + self.medname

application/views.py
from django.shortcuts import render, redirect
from . import logic
import mysql.connector as mysql
from django.contrib.auth.decorators import login_required
from .models import MedicineDet
from django.contrib.auth import logout

id = ''
license = ''
name = ''
username = ''
add = ''
owner = ''
contact = ''
password = ''

# For login action for Medicals
def loginaction(request):
    global username, password
    if request.method == 'POST':
        m = mysql.connect(host="localhost", user="root", password="Idevansh@22", database="medicals")
        cursor = m.cursor()
        d = request.POST
        for key, value in d.items():
            if key == 'Username':
                username = value
            if key == 'Password':
                password = value
        c = f"select * from owners where Username='{username}' and Password='{password}'"
        cursor.execute(c)
        t=tuple(cursor.fetchall())
        request.session['logindetails'] = {'medshop': t[0][2], 'medadd': t[0][4], 'medowner': t[0][5], 'medcontact': t[0][6]}

        if t==():
            return render(request, 'application/index.html')
        else:
            return redirect('pharmafriend:addnames')
    return render(request, 'application/login_med.html')


# For signup action of Medicals
def signupaction(request):
    global id, license, name, username, add, owner, contact, password
    if request.method == 'POST':
        m = mysql.connect(host="localhost", user="root", password="Idevansh@22", database="medicals")
        cursor = m.cursor()
        d = request.POST
        for key, value in d.items():
            if key == 'ID':
                id = value
            if key == 'License':
                license = value
            if key == 'Name':
                name = value
            if key == 'Username':
                username = value
            if key == 'Address':
                add = value
            if key == 'Owner':
                owner = value
            if key == 'Contact':
                contact = value
            if key == 'Password':
                password = value
        c = f"insert into owners(ID, License, Name, Username, Adress, Owner, Contact, Password) Values('{id}','{license}','{name}','{username}','{add}','{owner}','{contact}','{password}')"
        cursor.execute(c)
        m.commit()
    return render(request, 'application/signup_med.html')

def logoutmeds(request):
    logout(request)
    return redirect('pharmafriend:homepage')

def Homepage(request):
    return render(request, 'application/index.html')

def Pharmacy(request):
    return render(request, 'application/pharmacy.html')

# For medicals to add medicines
def AddMeds(request):
    print("Login Done")
    if request.method == 'POST':
        print("Login done")
        # get user inputs
        medicalshop = request.POST.get('shopname')
        medicalowner = request.POST.get('medown')
        medicalcontact = request.POST.get('medcontact')
        medicaladdress = request.POST.get('medadd')
        medicinename = str(request.POST.get('medname')).lower()
        medicinepower = request.POST.get('medpow')
        medicinextra = request.POST.get('medext')
        medicinquant = request.POST.get('medquan')
        medicineexp = request.POST.get('medexp')

        # create objects for models
        m = MedicineDet(medadd=medicaladdress,medowner=medicalowner,medcontact=medicalcontact,medshop=medicalshop,medname=medicinename,medextra=medicinextra,medpow=medicinepower,medquan=medicinquant,medexp=medicineexp)
        m.save()

        return redirect('pharmafriend:addnames')

    return render(request, 'application/addmeds.html')


# To locate Pharmacies
def Locate(request):
    if request.method == 'POST':
        medicine_name1 = str(request.POST['medicine-name'])
        medicine_name1 = medicine_name1.lower()
        aquery = MedicineDet.objects.filter(medname__startswith = medicine_name1)
        a = aquery.values_list()
        
        pharma = []
        for i in range(len(a)):
            pharmatemp = {}
            pharmatemp.update({"No": i+1, "MedAdd": a[i][1], "Medown": a[i][2], "Medcontact": a[i][3]
            ,"MedName": a[i][4],"MedAbr": a[i][6] + ' ' + str(a[i][7]),"MedQuan": a[i][8]})
            pharma.append(pharmatemp)
        
        context = {'pharmalist': pharma}
        return render(request, 'application/medical.html', context=context)
    return render(request, 'application/medical.html')

# To search Medicine 
def Search(request):
    if request.method == 'POST':
        medicine_name = request.POST['contact-name']
        if len(medicine_name) == 0:
            return redirect('pharmafriend:searchpage')
    # request.session.medicine
        if len(medicine_name) != 0:
            Search.med_name_mrp, Search.med_name_link = logic.didyoumean(medicine_name)
            request.session['medicine'] = Search.med_name_mrp
            return redirect('pharmafriend:storepage')
        else:
            return render(request, 'application/search-med.html')
    return render(request, 'application/search-med.html')


# To get Medicine Info
def Store(request):
    if request.method == 'POST':
        Store.medicine_selected = request.POST['meddropdown']
        medlink = Search.med_name_link[Store.medicine_selected]
        meddetails = logic.getinfo_onemg(medlink)
        Store.apollo, apolloops, Store.netmeds, netmedsops, Store.pharm, pharmops = logic.combined(Store.medicine_selected)
        
        request.session['medicineinfo'] = meddetails
        request.session['compareapolloops'] = apolloops
        request.session['comparenetmedsops'] = netmedsops
        request.session['comparepharmops'] = pharmops

        return redirect('pharmafriend:medicinepage')
    else:
        return render(request, 'application/shop.html')
        
# For comparision
def Medicine(request):
    if request.method == 'POST':
        medicine_selected_apollo = request.POST['meddropdownapollo']
        medicine_selected_pharm = request.POST['meddropdownpharm']
        medicine_selected_netmeds = request.POST['meddropdownnetmeds']
        
        apollo_details = Store.apollo[medicine_selected_apollo]
        pharm_details = Store.pharm[medicine_selected_pharm]
        netmeds_details = Store.netmeds[medicine_selected_netmeds]

        context = {"apollodet": apollo_details, "pharmdet": pharm_details, "netmedsdet": netmeds_details}
        # context1 = {"apollodet": medicine_selected_apollo, "pharmdet": medicine_selected_pharm, "netmedsdet": medicine_selected_netmeds}
        return render(request, 'application/comparison.html', context=context)
    else:
        pass
    return render(request, 'application/comparison.html')

# To search for government Kendras
def GovMeds(request):
    if request.method == 'POST':
        if request.POST.get("form_type") == 'formOne':
            #Handle Elements from first Form
            GovMeds.state_name_main = request.POST['govdropdownstate']
            dist_list = logic.getgovdist(GovMeds.state_name_main)
            context = {"districts": dist_list}
            return render(request, 'application/gov-vendor.html', context=context)

        if request.POST.get("form_type") == 'formTwo':
            dist_name = request.POST['govdropdowndistrict']
            govmeds = logic.getgovmeds(GovMeds.state_name_main, dist_name)
            govproducts, num = logic.getgovproducts()
            context1 = {"govmeds": govmeds, "govproducts": govproducts, "total": num}
            return render(request, 'application/gov-vendor.html', context=context1)


    return render(request, 'application/gov-vendor.html')

# To send email to doctor
@login_required(login_url = "accounts:loginuser")
def Doctor(request):
    user = request.user
    context = {
        'email': user.email
    }
    return render(request, 'application/doc-advice.html', context=context)

# About page
def About(request):
    return render(request, 'application/about.html')

# Contach us page
def Contact(request):
    return render(request, 'application/contact.html')

def error_400(request, exception):
    return render(request, 'application/errorpage.html')

def error_404(request, exception):
    return render(request, 'application/errorpage.html')

def error_500(request):
    return render(request, 'application/errorpage.html')

application/templates/application/addmeds.html
{% extends 'application/base.html' %}
{% load static %}

{% block content %}
  <div class="page">
    <div id="preloader" class="blobs-wrapper">
        <div class="grp-bgcolor-skincolor loader-blob"></div>
    </div>
    <div class="bg-light py-3">
      <div class="container">
        <div class="row" style="display: flex;justify-content: space-between;">
          <div class="col-md-5 mb-0">
            <a href="{% url 'pharmafriend:homepage' %}" style="text-decoration: none;">Home</a><span class="mx-2 mb-0">/</span>
            <a style="text-decoration: none;">Pharmacy</a><span class="mx-2 mb-0">/</span>
            <a style="text-decoration: none;">Login</a><span class="mx-2 mb-0">/</span>
            <a style="text-decoration: none;">Add Medicines</a>
          </div>
          <button style="float: right;" class="btn btn-danger"><a style="padding: 5px 10px;text-decoration: none;color:white;left: 100px;" href="{% url 'pharmafriend:logoutmeds' %}">Logout</a></button>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12" style="margin-top: 10px;">
          <div class="card">
            <div class="card-body">
              <form action="" method="POST">
                {% csrf_token %}
                <div class="md-3">
                    <label for='shopname'><b>Pharmacy Name :</b></label>
                    <input class="form-control" type='text' placeholder='Enter name of Pharmacy/Medical' name='shopname' value="{{request.session.logindetails.medshop}}" required><br>
                </div>
                <div class="md-3">
                    <label for='medown'><b>Owner Name:</b></label>
                    <input class="form-control" type='text' placeholder='Enter name of Pharmacy Owner' name='medown' value="{{request.session.logindetails.medowner}}" required><br>
                </div>
                <div class="med-3">
                    <label for='medcontact'><b>Contact No:</b></label>
                    <input class="form-control" type='text' placeholder='Enter Mobile/Telephone No.' name='medcontact' value="{{request.session.logindetails.medcontact}}" required><br>
                </div>
                <div class="md-3">
                    <label for='medadd'><b>Address:</b></label>
                    <textarea class="form-control" style="vertical-align: top;" id="medadd" placeholder="Enter Address of Medical Shop" name="medadd" rows="4" cols="100" required>{{request.session.logindetails.medadd}}</textarea><br>
                </div>
                <div class="md-3">
                    <label for="medname"><b>Medicine Name:</b></label>
                    <input class="form-control" type="text" placeholder="Enter name of Medicine" name="medname" id="medname" required>
                </div>
                
                <div class="md-3">
                    <label for="medpow"><b>Medicine Power:</b></label>
                    <input class="form-control" type="text" placeholder="Enter power of Medicine" name="medpow" id="medpow">
                </div>
                <div class="md-3">
                    <label for="medext"><b>Medicine Abbrevation:</b></label>
                    <input class="form-control" type="text" placeholder="Enter abbrevation of Medicine" name="medext" id="medext">
                </div>
                
                <div class="md-3">
                    <label for="medquan"><b>Medicine Quantity:</b></label>
                    <input class="form-control" type="number" name="medquan" id="medquan">
                </div>
                
                <div class="md-3">
                    <label for="medexp"><b>Medicine Expiry:</b></label>
                    <input class="form-control" type="date" name="medexp" id="medexp" required>
                </div>
                <div class="container text-center my-2">
                    <input class="btn btn-info" type="submit" value="Submit">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
        const FORM = document.querySelector('form');
        const CSRFToken = document.cookie.split('; ').find(row => row.startsWith('csrftoken=')).split('=')[1];
        // If the user logs out then logs in again, this will use the new Cookie CSRF Token and work
        document.querySelector('[name="csrfmiddlewaretoken"]').value = CSRFToken;
    </script>
</body>
</html>
{% endblock content %}

application/templates/application/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>PharmaFriend</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
  {% load static %}<link rel="stylesheet" href="{% static 'application/CSS/bootstrap.min.css' %}">
  {% load static %}<link rel="stylesheet" href="{% static 'application/CSS/magnific-popup.css' %}">
  {% load static %}<link rel="stylesheet" href="{% static 'application/CSS/jquery-ui.css' %}">
  {% load static %}<link rel="stylesheet" href="{% static 'application/CSS/owl.carousel.min.css' %}">
  {% load static %}<link rel="stylesheet" href="{% static 'application/CSS/owl.theme.default.min.css' %}">
  {% load static %}<link rel="stylesheet" href="{% static 'application/CSS/aos.css' %}">
  {% load static %}<link rel="stylesheet" href="{% static 'application/CSS/style.css' %}">
  {% load static %}<link rel="stylesheet" href="{% static 'consultvideo/css/style.css' %}">
  <!--Font Awesome -->
  <script src="https://kit.fontawesome.com/89baad1ea2.js" crossorigin="anonymous"></script>
</head> 

<body>
    <div class="site-navbar py-2">
        <div class="container">
        <div class="d-flex align-items-center justify-content-between">
            <div class="logo">
            <div class="site-logo">
                <a href="{% url 'pharmafriend:homepage' %}" class="js-logo-clone">Pharma Friend</a>
            </div>
            </div>
            <div class="main-nav d-none d-lg-block">
            <nav class="site-navigation text-right text-md-center" role="navigation">
                <ul class="site-menu js-clone-nav d-none d-lg-block">
                    <!-- Home -->
                    {% if 'http://127.0.0.1:8000/' in request.path %}
                    <li class="active"><a href="{% url 'pharmafriend:homepage' %}">Home</a></li>
                    {% else %}
                        <li><a href="{% url 'pharmafriend:homepage' %}">Home</a></li>
                    {% endif %}
                    
                    <!-- Store -->
                    {% if 'Store' in request.path %}
                        <li class="active"><a href="{% url 'pharmastore:homepage' %}">Store</a></li>
                    {% else %}
                        <li><a href="{% url 'pharmastore:homepage' %}">Store</a></li>
                    {% endif %}

                    <!-- Consult Page -->
                    {% if 'Consult' in request.path %}
                        <li class="active"><a href="{% url 'Consult:create_room' %}">Consult</a></li>
                    {% else %}
                        <li><a href="{% url 'Consult:create_room' %}">Consult</a></li>
                    {% endif %}

                    <!-- Search Medicine -->
                    {% if 'Search' in request.path %}
                        <li class="active"><a href="{% url 'pharmafriend:searchpage' %}">Search Medicines</a></li>
                    {% else %}
                        <li><a href="{% url 'pharmafriend:searchpage' %}">Search Medicines</a></li>
                    {% endif %}
                        
                    <!-- Government Medicines -->
                    {% if 'GovMeds' in request.path %}
                        <li class="active"><a href="{% url 'pharmafriend:govmeds' %}">Government Vendors</a></li>
                    {% else %}
                        <li><a href="{% url 'pharmafriend:govmeds' %}">Government Vendors</a></li>
                    {% endif %}

                    <!-- Locate Page -->
                    <!-- {% if 'Locate' in request.path %}
                        <li class="active"><a href="{% url 'pharmafriend:locatepage' %}">Locate Pharmacy</a></li>
                    {% else %}
                        <li><a href="{% url 'pharmafriend:locatepage' %}">Locate Pharmacy</a></li>
                    {% endif %} -->


                    <!-- About Page -->
                    {% if 'About' in request.path %}
                        <li class="active"><a href="{% url 'pharmafriend:aboutpage' %}">About</a></li>
                    {% else %}
                        <li><a href="{% url 'pharmafriend:aboutpage' %}">About</a></li>
                    {% endif %}
                </ul>
            </nav>
            </div>
            <div>      
                {% if user.id is None %}   
                    <div class="widget-header">
                        <small class="title text-muted">Welcome guest!</small>
                        <div>
                            <a href="{% url 'accounts:loginuser' %}">Sign in</a> <span class="dark-transp"> | </span>
                            <a href="{% url 'accounts:registeruser' %}"> Register</a>
                        </div>
                    </div>
                {% else %}
                    <div class="widget-header">
                        <small class="title text-muted">Welcome {{user.first_name}}</small>
                        <div> 
                            <a href="{% url 'accounts:logoutuser' %}">Logout</a> <span class="dark-transp"> | </span>
                            <a href="{% url 'accounts:dashboarduser' %}"> Dashboard</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    {% block content %}
        <!-- content -->
    {% endblock content %}

    <footer class="site-footer">
        <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
            <div class="block-7">
                <h3 class="footer-heading mb-4">About Us</h3>
                <p>We are with a mission of providing medicines to the customer at an affordable rate by price comparison and increasing awareness on Medicine prices and relevant information</p>
            </div>  
            </div>
            <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
            <h3 class="footer-heading mb-4">Quick Links</h3>
            <ul class="list-unstyled">
            <li><a href="{% url 'pharmafriend:homepage' %}">Home</a></li>
            <li><a href="{% url 'pharmafriend:searchpage' %}">Search Medicines</a></li>
            <li><a href="{% url 'pharmafriend:govmeds' %}">Government Vendors</a></li>
            <li><a href="{% url 'pharmafriend:locatepage' %}">Locate Pharmacy</a></li>
            <li><a href="{% url 'pharmafriend:pharmacy' %}">Pharmacy Zone</a></li>
            <!-- <li><a href="{% url 'pharmafriend:aboutpage' %}">About</a></li>
            <li><a href="{% url 'pharmafriend:contactpage' %}">Contact</a></li> -->
            </ul>
            </div>

            <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
                <h3 class="footer-heading mb-4">Contact Info</h3>
                <ul class="list-unstyled">
                <li class="address">KJSIT Sion, Mumbai, Maharashtra, India</li>
                <li class="phone"><a>+91 77385 74300</a></li>
                <li class="email"><a href="#" onclick="sendEmail('gammabytessup@gmail.com', 'Communication with GammaBytes', 'BODY');">gammabytessup@gmail.com</a></li>
                </ul>
            </div>
            </div>
        </div>
        
        </div>
        <div class="row pt-5 mt-5 text-center">
            <div class="col-md-12">
            <p>
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved | Website made by Gammabyte Pvt Ltd.
            
            </p>
            </div>

        </div>
    </footer>

    <script>
        function sendEmail(to, subject, body) {
            window.open('https://mail.google.com/mail/u/0/?view=cm&fs=1&to=' + to + '&su=' + subject + '&body=' + body);
        }
    </script>

    

application/templates/application/doc-advice.html
{% extends 'application/base.html' %}
{% load static %}


{% block content %}
    <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px;margin-top: 100px;">
        Your Consultation Request is under processing, our selected representative will contact you in 15-20mins 
        <br><br>
        Got a consultation room no? <a href="{% url 'Consult:room' %}">Join now</a> 
    </div>
{% endblock content %}
    

application/templates/application/pharmacy.html
{% extends 'application/base.html' %}
{% load static %}

{% block content %}  
  <div class="page">
    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-5 mb-0">
            <a href="{% url 'pharmafriend:homepage' %}" style="text-decoration: none;">Home</a><span class="mx-2 mb-0">/</span>
            <a style="text-decoration: none;">Pharmacy</a>
          </div>
        </div>
      </div>
    </div>
      
    <div class="container">
      <div class="row" style="display: flex;justify-content: center">
        <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
          <div class="banner-wrap bg-primary h-100">
            <a href="{% url 'pharmafriend:signupmed' %}" class="h-100">
              <h5>Register</h5>
              <p>
                Add inventory and medicine details
              </p>
            </a>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 mb-4 mb-lg-0" style="background-color: rgb(31, 7, 214);">
          <div class="banner-wrap h-100">
            <a href="{% url 'pharmafriend:locatepage' %}" class="h-100" style="background-color: rgb(31, 7, 214);">
              <h5>Locate</h5>
              <p>
                Check availability of medicines in local pharmacies
              </p>
            </a>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
          <div class="banner-wrap h-100">
            <a href="{% url 'pharmafriend:loginmed' %}" class="h-100">
              <h5>Login</h5>
              <p>
                Already a pharmabud ?
              </p>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>  
</body>
</html>
{% endblock content %}